import { routing } from "@/i18n/routing";
import MainProviders from "@/shared/providers/MainProviders";
import Footer from "@/shared/components/Footer";
import Header from "@/shared/components/header/Header";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import "../globals.css";
import { Outfit, Noto_Sans } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-outfit",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-noto-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Validate locale
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering for next-intl
  setRequestLocale(locale);

  return (
    <html lang={locale} className={`${outfit.variable} ${notoSans.variable}`}>
      <body className={`antialiased ${outfit.className}`}>
        <MainProviders locale={locale}>
          <main className="min-h-screen">{children}</main>
        </MainProviders>
      </body>
    </html>
  );
}
